# -*- coding: utf-8 -*-
"""ChatGPT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFPbSEZyr-M4J1urUQDxF2eSZiHrT4x3
"""

# !pip install requests

import requests

def chatGPT(text):
  url = "https://api.openai.com/v1/completions"
  headers = {
      "Content-Type": "application/json",
      "Authorization": "Bearer YOUR-API-KEY",
  }
  data = {
      "model": "text-davinci-003",
      "prompt": text,
      "max_tokens": 4000,
      "temperature": 1.0,
  }
  response = requests.post(url, headers=headers, json=data)
  output = response.json()['choices'][0]['text']

  return print(output)

chatGPT('Generate a romantic song ever for my crush')

